name: mocha
description: A simple caching library.
version: 0.0.2
homepage: https://github.com/thekeenant/mocha
author: Keenan Thompson <keenan@keenant.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.6.4
